package GUIFrames;

import myMovies_new.GuiUtils;
import java.awt.event.*;
import java.util.*;
import myMovies_new.UpdateDB;


public class MainFrame extends javax.swing.JFrame {
    ArrayList<String> favoriteList;

    public MainFrame(ArrayList favoriteList) {

        this.favoriteList = favoriteList;
        initComponents();
        this.setTitle("myMovies_new");
        this.setVisible(true);
        this.addWindowListener(exitListener);
    }
    
    //exit Listener ώστε να γίνεται ερώτηση πρίν το κλείσιμο 
    WindowListener exitListener = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            GuiUtils.exitProgram();
        }
    };
    
    //Κάθε φορά που ενεργοποιείται η φόρμα πάει στο κέντρο
    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
         this.setLocationRelativeTo(null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RetreiveAndSaveMovieDataButton = new javax.swing.JButton();
        FavouriteListManagementButton = new javax.swing.JButton();
        SearchMovieButton = new javax.swing.JButton();
        StatiticsButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RetreiveAndSaveMovieDataMenuItem = new javax.swing.JMenuItem();
        FavouriteListManagementMenuItem = new javax.swing.JMenuItem();
        SearchMovieMenuItem = new javax.swing.JMenuItem();
        StatiticsMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ExitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        RetreiveAndSaveMovieDataButton.setText("Retreive And Save Movie Data");
        RetreiveAndSaveMovieDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetreiveAndSaveMovieDataButtonActionPerformed(evt);
            }
        });

        FavouriteListManagementButton.setText("Favourite List Management");
        FavouriteListManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavouriteListManagementButtonActionPerformed(evt);
            }
        });

        SearchMovieButton.setText("Search Movie");
        SearchMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMovieButtonActionPerformed(evt);
            }
        });

        StatiticsButton.setText("Statitics");
        StatiticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatiticsButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("myMovies");

        RetreiveAndSaveMovieDataMenuItem.setText("1. Retreive and Save Movie Data");
        RetreiveAndSaveMovieDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetreiveAndSaveMovieDataMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(RetreiveAndSaveMovieDataMenuItem);

        FavouriteListManagementMenuItem.setText("2. Favourite List Management");
        FavouriteListManagementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavouriteListManagementMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(FavouriteListManagementMenuItem);

        SearchMovieMenuItem.setText("3. Search Movie");
        SearchMovieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMovieMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SearchMovieMenuItem);

        StatiticsMenuItem.setText("4. Statitics");
        StatiticsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatiticsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(StatiticsMenuItem);
        jMenu1.add(jSeparator1);

        ExitMenuItem.setText("5. Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RetreiveAndSaveMovieDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FavouriteListManagementButton)
                        .addGap(96, 96, 96)
                        .addComponent(SearchMovieButton)
                        .addGap(79, 79, 79)
                        .addComponent(StatiticsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(ExitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RetreiveAndSaveMovieDataButton)
                    .addComponent(FavouriteListManagementButton)
                    .addComponent(SearchMovieButton)
                    .addComponent(StatiticsButton))
                .addGap(71, 71, 71)
                .addComponent(ExitButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void RetreiveAndSaveMovieDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetreiveAndSaveMovieDataMenuItemActionPerformed
        // TODO add your handling code here:
        UpdateDB.UpdateAllDB();
    }//GEN-LAST:event_RetreiveAndSaveMovieDataMenuItemActionPerformed

    private void FavouriteListManagementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavouriteListManagementMenuItemActionPerformed
        // TODO add your handling code here:
        new FavouriteListFrame(this, this, favoriteList);
    }//GEN-LAST:event_FavouriteListManagementMenuItemActionPerformed

    private void SearchMovieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMovieMenuItemActionPerformed
        // TODO add your handling code here:
        new MovieSearchFrame(this, this, favoriteList);
    }//GEN-LAST:event_SearchMovieMenuItemActionPerformed

    private void StatiticsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatiticsMenuItemActionPerformed
        // TODO add your handling code here:
        new StatiticsFrame(this, this, favoriteList);
    }//GEN-LAST:event_StatiticsMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
        GuiUtils.exitProgram();
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void RetreiveAndSaveMovieDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetreiveAndSaveMovieDataButtonActionPerformed
        // TODO add your handling code here:
        UpdateDB.UpdateAllDB();
    }//GEN-LAST:event_RetreiveAndSaveMovieDataButtonActionPerformed

    private void FavouriteListManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavouriteListManagementButtonActionPerformed
        // TODO add your handling code here:
        new FavouriteListFrame(this, this, favoriteList);
    }//GEN-LAST:event_FavouriteListManagementButtonActionPerformed

    private void SearchMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMovieButtonActionPerformed
        // TODO add your handling code here:
        new MovieSearchFrame(this, this, favoriteList);
    }//GEN-LAST:event_SearchMovieButtonActionPerformed

    private void StatiticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatiticsButtonActionPerformed
        // TODO add your handling code here:
        new StatiticsFrame(this, this, favoriteList);
    }//GEN-LAST:event_StatiticsButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        GuiUtils.exitProgram();
    }//GEN-LAST:event_ExitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JButton FavouriteListManagementButton;
    private javax.swing.JMenuItem FavouriteListManagementMenuItem;
    private javax.swing.JButton RetreiveAndSaveMovieDataButton;
    private javax.swing.JMenuItem RetreiveAndSaveMovieDataMenuItem;
    private javax.swing.JButton SearchMovieButton;
    private javax.swing.JMenuItem SearchMovieMenuItem;
    private javax.swing.JButton StatiticsButton;
    private javax.swing.JMenuItem StatiticsMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
